### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by bhaan** [bhaan/my-app-analytics#2]
... to something better

**Comment by jcrevier** [comment]
If were going to do namespaces, we should come up with that better name too.

ButtonStat

PressCounter

ButtonPressCounter

UI-button-stat

I kinda like ButtonStat. But maybe its too narrow?

**Comment by bhaan** [comment]
ButtonStat is a bit narrow. The goal was to keep this open ended, even if I'm mostly using it for button taps.

My next thought was AppStat, but that already seems to be use by a few other projects/products that are kinda but not really related.

How bout Apptivity? App and Activity smashed together. Meaning I'm gathering information about the activity of the app. Just a thought.

**Comment by jcrevier** [comment]
I like Apptivity. We could go with that.

**Comment by bhaan** [comment]
Go ahead and rename the files and classes that need changing

**Comment by bhaan** [comment]
Also, from the looks of it. You'll have to rename your fork of the repo yourself. My renaming doesn't effect yours

**Comment by jcrevier** [comment]
Hmm. I have your repo set as upstream, so I should be able to pull it over
somehow.

**Comment by bhaan** [comment]
the upstream you have setup only applies to the git repository, which is different then the github repository. The name of the github repository has nothing to do with anything stored in the actual git repo (all of our files). I just assumed that github would play nice and apply my new name to any forked repository.
